# Auto Labeler rulse using https://github.com/actions/labeler
#

# 'fix' in title/branch -> bug
# 'feat' in title/branch -> enhancement
# 'repo' in title/branch OR changes to ~/.github/ -> repo
# 'bug_fallthrough' for everything else except auto 
#
# - [ ] need to look at title.     waiting on https://github.com/actions/labeler/pull/866

# Add 'enhancement' label to any PR where the head branch name contains `feat`
enhancement:
 - head-branch: [feat, Feat, FEAT]

 # Add 'repo' label to any PR where the head branch name contains `repo` 
 # or files in the .github dir
repo:
- any:
  - head-branch: [repo, Repo, REPO, ci, CI]
  - changed-files:
    - any-glob-to-any-file: .github

 # Add 'bug' label to any PR where the head branch name contains `fix` or `bug` as the prefix.
bugfix:
  - head-branch: [^fix, ^bug, ^Fix, ^FIX, ^Bug, ^BUG]

# our fallback - bug except repo, feat, or automated pipelines
# bug_fallthrough:
# - all:
#   - head-branch: ['^((?!feat).)*$', '^((?!repo).)*$', '^((?!renovate).)*$', '^((?!scheduled).)*$']

