# .github/release.yml

changelog:
  categories:
    - title: 🏗️ Features
      labels:
        - enhancement
      exclude:
        labels:
          - dependencies

    - title: 🛠️Fixes
      labels:
        - '*'
      exclude:
        labels:
          - enhancement
          - dependencies
          - repo

    - title: 👷Dependencies
      labels:
        - dependencies

    - title: 🧱Repo
      labels:
        - repo
