# .github/release.yml

changelog:
  categories:
    - title: 🛠️Fixes & Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👷Dependencies
      labels:
        - dependencies
