# .github/release.yml - GitHub Release Notes Configuration

changelog:
  exclude:
    labels:
      - dependencies
      - automation
      - release
      - repo
      - skip-changelog
      - chore
      - ci
      - build
      - testing
      - test
      - refactor
      - documentation
      - translation
    authors:
      - renovate[bot]
      - dependabot[bot]
      - github-actions[bot]

  categories:
    - title: 🏗️ Features
      labels:
        - enhancement
        - feature
    - title: 🖥️ Desktop
      labels:
        - desktop
    - title: 🛠️ Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 📝 Other Changes
      labels:
        - '*'
