include "#!./gradlew -q :desktop:printConveyorConfig"

app {
  display-name = "Meshtastic"
  rdns-name = "org.meshtastic.desktop"
  vcs-url = "https://github.com/meshtastic/Meshtastic-Android"
  license = "GPL-3.0"
  
  icons = "desktop/src/main/resources/icon.png"

  site.base-url = "https://github.com/meshtastic/Meshtastic-Android/releases/latest/download"
}