pull_request_labels:
  - automation
  - l10n
files:
  - source: /**/src/commonMain/composeResources/values/strings.xml
    translation: /%original_path%-%two_letters_code%/strings.xml
    translate_attributes: 0
    content_segmentation: 0
