/*
 * Copyright (c) 2025-2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
@file:Suppress("LongMethod")

package org.meshtastic.core.ui.emoji

/** A single emoji entry with optional skin-tone support and search keywords. */
internal data class Emoji(
    val base: String,
    val keywords: List<String> = emptyList(),
    val supportsSkinTone: Boolean = false,
)

/** A named category of emojis with an icon emoji for the tab. */
internal data class EmojiCategory(val name: String, val icon: String, val emojis: List<Emoji>)

/** Unicode skin tone modifiers (Fitzpatrick scale). */
internal enum class SkinTone(val modifier: String, val label: String, val preview: String) {
    DEFAULT("", "Default", "👋"),
    LIGHT("\uD83C\uDFFB", "Light", "👋🏻"),
    MEDIUM_LIGHT("\uD83C\uDFFC", "Medium-Light", "👋🏼"),
    MEDIUM("\uD83C\uDFFD", "Medium", "👋🏽"),
    MEDIUM_DARK("\uD83C\uDFFE", "Medium-Dark", "👋🏾"),
    DARK("\uD83C\uDFFF", "Dark", "👋🏿"),
}

/**
 * Applies a skin tone modifier to a base emoji string. Only works correctly for single-codepoint emojis that support
 * skin tones.
 */
internal fun Emoji.withSkinTone(tone: SkinTone): String {
    if (!supportsSkinTone || tone == SkinTone.DEFAULT) return base
    // Insert the modifier after the first code point (which may be a surrogate pair)
    val firstChar = base[0]
    val charCount = if (firstChar.isHighSurrogate() && base.length > 1) 2 else 1
    val baseChar = base.substring(0, charCount)
    val after = base.substring(charCount)
    return baseChar + tone.modifier + after
}

// ── Emoji Catalog ──────────────────────────────────────────────────────────────

@Suppress("LargeClass", "MaxLineLength")
internal object EmojiData {
    private fun e(base: String, vararg kw: String, skin: Boolean = false) = Emoji(base, kw.toList(), skin)

    val categories: List<EmojiCategory> =
        listOf(smileys(), people(), nature(), food(), travel(), activities(), objects(), symbols(), flags())

    /** Flat list for search. */
    val all: List<Emoji> by lazy { categories.flatMap { it.emojis } }

    // ── Categories ─────────────────────────────────────────────────────────────

    private fun smileys() = EmojiCategory(
        name = "Smileys & Emotion",
        icon = "😀",
        emojis =
        listOf(
            e("😀", "grin", "happy"),
            e("😃", "smile", "happy"),
            e("😄", "laugh", "happy"),
            e("😁", "grin", "teeth"),
            e("😆", "laugh", "squint"),
            e("😅", "sweat", "smile"),
            e("🤣", "rofl", "laugh"),
            e("😂", "joy", "tears"),
            e("🙂", "slight", "smile"),
            e("🙃", "upside", "down"),
            e("🫠", "melting", "face"),
            e("😉", "wink"),
            e("😊", "blush", "happy"),
            e("😇", "halo", "angel"),
            e("🥰", "hearts", "love"),
            e("😍", "heart", "eyes"),
            e("🤩", "star", "struck"),
            e("😘", "kiss", "heart"),
            e("😗", "kiss"),
            e("😚", "kiss", "blush"),
            e("😙", "kiss", "smile"),
            e("🥲", "smile", "tear"),
            e("😋", "yum", "delicious"),
            e("😛", "tongue"),
            e("😜", "wink", "tongue"),
            e("🤪", "zany", "crazy"),
            e("😝", "squint", "tongue"),
            e("🤑", "money", "face"),
            e("🤗", "hug"),
            e("🤭", "shush", "oops"),
            e("🫢", "peek", "hand"),
            e("🫣", "peeking", "shy"),
            e("🤫", "quiet", "shush"),
            e("🤔", "think", "hmm"),
            e("🫡", "salute"),
            e("🤐", "zipper", "mouth"),
            e("🤨", "raised", "eyebrow"),
            e("😐", "neutral"),
            e("😑", "expressionless"),
            e("😶", "mute", "silent"),
            e("🫥", "dotted", "invisible"),
            e("😶‍🌫️", "fog", "cloudy"),
            e("😏", "smirk"),
            e("😒", "unamused"),
            e("🙄", "eye", "roll"),
            e("😬", "grimace"),
            e("🫨", "shaking"),
            e("😮‍💨", "exhale", "sigh"),
            e("🤥", "liar", "pinocchio"),
            e("🫠", "melting"),
            e("😌", "relieved"),
            e("😔", "pensive", "sad"),
            e("😪", "sleepy"),
            e("🤤", "drool"),
            e("😴", "sleep", "zzz"),
            e("😷", "mask", "sick"),
            e("🤒", "thermometer", "sick"),
            e("🤕", "bandage", "hurt"),
            e("🤢", "nausea", "sick"),
            e("🤮", "vomit"),
            e("🥵", "hot", "sweat"),
            e("🥶", "cold", "freeze"),
            e("🥴", "woozy", "drunk"),
            e("😵", "dizzy"),
            e("😵‍💫", "spiral", "dizzy"),
            e("🤯", "mind", "blown"),
            e("🤠", "cowboy"),
            e("🥳", "party"),
            e("🥸", "disguise"),
            e("😎", "cool", "sunglasses"),
            e("🤓", "nerd"),
            e("🧐", "monocle"),
            e("😕", "confused"),
            e("🫤", "diagonal", "mouth"),
            e("😟", "worried"),
            e("🙁", "frown"),
            e("☹️", "frown"),
            e("😮", "open", "mouth"),
            e("😯", "hushed"),
            e("😲", "astonished"),
            e("😳", "flushed"),
            e("🥺", "pleading"),
            e("🥹", "holding", "tears"),
            e("😦", "frown", "open"),
            e("😧", "anguished"),
            e("😨", "fearful"),
            e("😰", "anxious", "sweat"),
            e("😥", "sad", "relieved"),
            e("😢", "cry"),
            e("😭", "sob", "cry"),
            e("😱", "scream"),
            e("😖", "confounded"),
            e("😣", "persevere"),
            e("😞", "disappointed"),
            e("😓", "downcast", "sweat"),
            e("😩", "weary"),
            e("😫", "tired"),
            e("🥱", "yawn"),
            e("😤", "huff", "triumph"),
            e("😡", "angry", "rage"),
            e("😠", "angry"),
            e("🤬", "swear", "cursing"),
            e("😈", "devil", "smile"),
            e("👿", "devil", "angry"),
            e("💀", "skull", "dead"),
            e("☠️", "skull", "crossbones"),
            e("💩", "poop"),
            e("🤡", "clown"),
            e("👹", "ogre"),
            e("👺", "goblin"),
            e("👻", "ghost"),
            e("👽", "alien"),
            e("👾", "space", "invader"),
            e("🤖", "robot"),
            e("😺", "cat", "smile"),
            e("😸", "cat", "grin"),
            e("😹", "cat", "joy"),
            e("😻", "cat", "heart"),
            e("😼", "cat", "smirk"),
            e("😽", "cat", "kiss"),
            e("🙀", "cat", "weary"),
            e("😿", "cat", "cry"),
            e("😾", "cat", "angry"),
            e("🙈", "see", "no", "evil"),
            e("🙉", "hear", "no", "evil"),
            e("🙊", "speak", "no", "evil"),
            e("❤️", "red", "heart", "love"),
            e("🧡", "orange", "heart"),
            e("💛", "yellow", "heart"),
            e("💚", "green", "heart"),
            e("💙", "blue", "heart"),
            e("💜", "purple", "heart"),
            e("🖤", "black", "heart"),
            e("🤍", "white", "heart"),
            e("🤎", "brown", "heart"),
            e("❤️‍🔥", "heart", "fire"),
            e("❤️‍🩹", "heart", "mending"),
            e("💔", "broken", "heart"),
            e("💕", "two", "hearts"),
            e("💞", "revolving", "hearts"),
            e("💓", "heartbeat"),
            e("💗", "growing", "heart"),
            e("💖", "sparkling", "heart"),
            e("💘", "cupid", "heart"),
            e("💝", "ribbon", "heart"),
            e("💟", "heart", "decoration"),
            e("💯", "hundred", "perfect"),
            e("💢", "anger"),
            e("💥", "boom", "collision"),
            e("💫", "dizzy", "star"),
            e("💦", "sweat", "droplets"),
            e("💨", "dash", "wind"),
            e("🕳️", "hole"),
            e("💬", "speech", "bubble"),
            e("💭", "thought", "bubble"),
            e("🗯️", "angry", "bubble"),
            e("💤", "zzz", "sleep"),
        ),
    )

    private fun people() = EmojiCategory(
        name = "People & Body",
        icon = "👋",
        emojis =
        listOf(
            e("👋", "wave", "hello", skin = true),
            e("🤚", "raised", "back", "hand", skin = true),
            e("🖐️", "hand", "splayed", skin = true),
            e("✋", "hand", "stop", skin = true),
            e("🖖", "vulcan", "spock", skin = true),
            e("🫱", "rightward", "hand", skin = true),
            e("🫲", "leftward", "hand", skin = true),
            e("🫳", "palm", "down", skin = true),
            e("🫴", "palm", "up", skin = true),
            e("🫷", "push", "left", skin = true),
            e("🫸", "push", "right", skin = true),
            e("👌", "ok", "perfect", skin = true),
            e("🤌", "pinched", "fingers", skin = true),
            e("🤏", "pinching", "hand", skin = true),
            e("✌️", "peace", "victory", skin = true),
            e("🤞", "crossed", "fingers", skin = true),
            e("🫰", "hand", "index", "thumb", skin = true),
            e("🤟", "love", "you", skin = true),
            e("🤘", "rock", "metal", skin = true),
            e("🤙", "call", "shaka", skin = true),
            e("👈", "point", "left", skin = true),
            e("👉", "point", "right", skin = true),
            e("👆", "point", "up", skin = true),
            e("🖕", "middle", "finger", skin = true),
            e("👇", "point", "down", skin = true),
            e("☝️", "point", "up", skin = true),
            e("🫵", "point", "you", skin = true),
            e("👍", "thumbs", "up", "like", skin = true),
            e("👎", "thumbs", "down", "dislike", skin = true),
            e("✊", "fist", "raised", skin = true),
            e("👊", "punch", "fist", skin = true),
            e("🤛", "fist", "left", skin = true),
            e("🤜", "fist", "right", skin = true),
            e("👏", "clap", skin = true),
            e("🙌", "raised", "hands", skin = true),
            e("🫶", "heart", "hands", skin = true),
            e("👐", "open", "hands", skin = true),
            e("🤲", "palms", "up", skin = true),
            e("🤝", "handshake"),
            e("🙏", "pray", "please", "thanks", skin = true),
            e("✍️", "writing", skin = true),
            e("💅", "nail", "polish", skin = true),
            e("🤳", "selfie", skin = true),
            e("💪", "muscle", "strong", skin = true),
            e("🦾", "mechanical", "arm"),
            e("🦿", "mechanical", "leg"),
            e("🦵", "leg", skin = true),
            e("🦶", "foot", skin = true),
            e("👂", "ear", skin = true),
            e("🦻", "ear", "hearing", skin = true),
            e("👃", "nose", skin = true),
            e("🧠", "brain"),
            e("🫀", "anatomical", "heart"),
            e("🫁", "lungs"),
            e("🦷", "tooth"),
            e("🦴", "bone"),
            e("👀", "eyes", "look"),
            e("👁️", "eye"),
            e("👅", "tongue"),
            e("👄", "lips", "mouth"),
            e("🫦", "biting", "lip"),
            e("👶", "baby", skin = true),
            e("🧒", "child", skin = true),
            e("👦", "boy", skin = true),
            e("👧", "girl", skin = true),
            e("🧑", "person", "adult", skin = true),
            e("👱", "blond", skin = true),
            e("👨", "man", skin = true),
            e("🧔", "beard", skin = true),
            e("👩", "woman", skin = true),
            e("🧓", "older", "person", skin = true),
            e("👴", "old", "man", skin = true),
            e("👵", "old", "woman", skin = true),
            e("🙍", "frown", "person", skin = true),
            e("🙎", "pout", "person", skin = true),
            e("🙅", "no", "gesture", skin = true),
            e("🙆", "ok", "gesture", skin = true),
            e("💁", "tipping", "hand", skin = true),
            e("🙋", "raising", "hand", skin = true),
            e("🧏", "deaf", "person", skin = true),
            e("🙇", "bow", skin = true),
            e("🤦", "facepalm", skin = true),
            e("🤷", "shrug", skin = true),
        ),
    )

    private fun nature() = EmojiCategory(
        name = "Animals & Nature",
        icon = "🐾",
        emojis =
        listOf(
            e("🐶", "dog", "puppy"),
            e("🐱", "cat", "kitten"),
            e("🐭", "mouse"),
            e("🐹", "hamster"),
            e("🐰", "rabbit", "bunny"),
            e("🦊", "fox"),
            e("🐻", "bear"),
            e("🐼", "panda"),
            e("🐻‍❄️", "polar", "bear"),
            e("🐨", "koala"),
            e("🐯", "tiger"),
            e("🦁", "lion"),
            e("🐮", "cow"),
            e("🐷", "pig"),
            e("🐸", "frog"),
            e("🐵", "monkey"),
            e("🐔", "chicken"),
            e("🐧", "penguin"),
            e("🐦", "bird"),
            e("🐤", "chick"),
            e("🦆", "duck"),
            e("🦅", "eagle"),
            e("🦉", "owl"),
            e("🦇", "bat"),
            e("🐺", "wolf"),
            e("🐗", "boar"),
            e("🐴", "horse"),
            e("🦄", "unicorn"),
            e("🐝", "bee", "honeybee"),
            e("🪱", "worm"),
            e("🐛", "bug"),
            e("🦋", "butterfly"),
            e("🐌", "snail"),
            e("🐞", "ladybug"),
            e("🐜", "ant"),
            e("🪰", "fly"),
            e("🪲", "beetle"),
            e("🪳", "cockroach"),
            e("🦟", "mosquito"),
            e("🦗", "cricket"),
            e("🕷️", "spider"),
            e("🦂", "scorpion"),
            e("🐢", "turtle"),
            e("🐍", "snake"),
            e("🦎", "lizard"),
            e("🦖", "dinosaur"),
            e("🦕", "sauropod"),
            e("🐙", "octopus"),
            e("🦑", "squid"),
            e("🦐", "shrimp"),
            e("🦞", "lobster"),
            e("🦀", "crab"),
            e("🐡", "blowfish"),
            e("🐠", "tropical", "fish"),
            e("🐟", "fish"),
            e("🐬", "dolphin"),
            e("🐳", "whale"),
            e("🐋", "whale"),
            e("🦈", "shark"),
            e("🦭", "seal"),
            e("🐊", "crocodile"),
            e("🐅", "tiger"),
            e("🐆", "leopard"),
            e("🦓", "zebra"),
            e("🦍", "gorilla"),
            e("🦧", "orangutan"),
            e("🐘", "elephant"),
            e("🦬", "bison"),
            e("🦛", "hippo"),
            e("🦏", "rhino"),
            e("🐪", "camel"),
            e("🐫", "camel", "two", "humps"),
            e("🦒", "giraffe"),
            e("🦘", "kangaroo"),
            e("🐃", "water", "buffalo"),
            e("🐂", "ox"),
            e("🐄", "cow"),
            e("🐎", "horse", "racing"),
            e("🐖", "pig"),
            e("🐏", "ram"),
            e("🐑", "sheep"),
            e("🦙", "llama"),
            e("🐐", "goat"),
            e("🦌", "deer"),
            e("🐕", "dog"),
            e("🐩", "poodle"),
            e("🦮", "guide", "dog"),
            e("🐕‍🦺", "service", "dog"),
            e("🐈", "cat"),
            e("🐈‍⬛", "black", "cat"),
            e("🐓", "rooster"),
            e("🦃", "turkey"),
            e("🦤", "dodo"),
            e("🦚", "peacock"),
            e("🦜", "parrot"),
            e("🦢", "swan"),
            e("🦩", "flamingo"),
            e("🕊️", "dove", "peace"),
            e("🐇", "rabbit"),
            e("🦝", "raccoon"),
            e("🦨", "skunk"),
            e("🦡", "badger"),
            e("🦫", "beaver"),
            e("🦦", "otter"),
            e("🦥", "sloth"),
            e("🐁", "mouse"),
            e("🐀", "rat"),
            e("🐿️", "chipmunk"),
            e("🦔", "hedgehog"),
            e("🌵", "cactus"),
            e("🎄", "christmas", "tree"),
            e("🌲", "evergreen", "tree"),
            e("🌳", "deciduous", "tree"),
            e("🌴", "palm", "tree"),
            e("🪵", "wood", "log"),
            e("🌱", "seedling", "sprout"),
            e("🌿", "herb"),
            e("☘️", "shamrock"),
            e("🍀", "four", "leaf", "clover"),
            e("🎍", "bamboo"),
            e("🪴", "potted", "plant"),
            e("🎋", "tanabata", "tree"),
            e("🍃", "leaf", "wind"),
            e("🍂", "fallen", "leaf"),
            e("🍁", "maple", "leaf"),
            e("🪺", "nest", "eggs"),
            e("🪹", "nest"),
            e("🍄", "mushroom"),
            e("🌾", "rice", "sheaf"),
            e("💐", "bouquet", "flowers"),
            e("🌷", "tulip"),
            e("🌹", "rose"),
            e("🥀", "wilted", "flower"),
            e("🪻", "hyacinth"),
            e("🌺", "hibiscus"),
            e("🌸", "cherry", "blossom"),
            e("🌼", "blossom"),
            e("🌻", "sunflower"),
            e("🌞", "sun", "face"),
            e("🌝", "moon", "face"),
            e("🌛", "moon", "quarter"),
            e("🌜", "moon", "quarter"),
            e("🌚", "new", "moon"),
            e("🌕", "full", "moon"),
            e("🌖", "waning", "moon"),
            e("🌗", "last", "quarter"),
            e("🌘", "waning", "crescent"),
            e("🌑", "new", "moon"),
            e("🌒", "waxing", "crescent"),
            e("🌓", "first", "quarter"),
            e("🌔", "waxing", "moon"),
            e("🌙", "crescent", "moon"),
            e("🌎", "earth", "americas"),
            e("🌍", "earth", "africa"),
            e("🌏", "earth", "asia"),
            e("🪐", "saturn", "planet"),
            e("💫", "dizzy", "star"),
            e("⭐", "star"),
            e("🌟", "glowing", "star"),
            e("✨", "sparkles"),
            e("⚡", "lightning", "zap"),
            e("☄️", "comet"),
            e("💥", "collision", "boom"),
            e("🔥", "fire", "hot"),
            e("🌪️", "tornado"),
            e("🌈", "rainbow"),
            e("☀️", "sun"),
            e("🌤️", "sun", "cloud"),
            e("⛅", "partly", "cloudy"),
            e("🌥️", "mostly", "cloudy"),
            e("☁️", "cloud"),
            e("🌦️", "rain", "sun"),
            e("🌧️", "rain"),
            e("⛈️", "thunderstorm"),
            e("🌩️", "lightning"),
            e("🌨️", "snow"),
            e("❄️", "snowflake"),
            e("☃️", "snowman"),
            e("⛄", "snowman"),
            e("🌬️", "wind"),
            e("💨", "dash", "wind"),
            e("🌫️", "fog"),
            e("🌊", "wave", "ocean"),
            e("💧", "droplet"),
            e("💦", "sweat", "splash"),
            e("☔", "umbrella", "rain"),
        ),
    )

    private fun food() = EmojiCategory(
        name = "Food & Drink",
        icon = "🍔",
        emojis =
        listOf(
            e("🍇", "grapes"),
            e("🍈", "melon"),
            e("🍉", "watermelon"),
            e("🍊", "orange", "tangerine"),
            e("🍋", "lemon"),
            e("🍌", "banana"),
            e("🍍", "pineapple"),
            e("🥭", "mango"),
            e("🍎", "apple", "red"),
            e("🍏", "apple", "green"),
            e("🍐", "pear"),
            e("🍑", "peach"),
            e("🍒", "cherries"),
            e("🍓", "strawberry"),
            e("🫐", "blueberries"),
            e("🥝", "kiwi"),
            e("🍅", "tomato"),
            e("🫒", "olive"),
            e("🥥", "coconut"),
            e("🥑", "avocado"),
            e("🍆", "eggplant"),
            e("🥔", "potato"),
            e("🥕", "carrot"),
            e("🌽", "corn"),
            e("🌶️", "hot", "pepper"),
            e("🫑", "bell", "pepper"),
            e("🥒", "cucumber"),
            e("🥬", "leafy", "green"),
            e("🥦", "broccoli"),
            e("🧄", "garlic"),
            e("🧅", "onion"),
            e("🥜", "peanuts"),
            e("🫘", "beans"),
            e("🌰", "chestnut"),
            e("🫚", "ginger"),
            e("🫛", "pea", "pod"),
            e("🍞", "bread"),
            e("🥐", "croissant"),
            e("🥖", "baguette"),
            e("🫓", "flatbread"),
            e("🥨", "pretzel"),
            e("🥯", "bagel"),
            e("🥞", "pancakes"),
            e("🧇", "waffle"),
            e("🧀", "cheese"),
            e("🍖", "meat", "bone"),
            e("🍗", "poultry", "leg"),
            e("🥩", "steak", "cut", "meat"),
            e("🥓", "bacon"),
            e("🍔", "burger", "hamburger"),
            e("🍟", "fries"),
            e("🍕", "pizza"),
            e("🌭", "hotdog"),
            e("🥪", "sandwich"),
            e("🌮", "taco"),
            e("🌯", "burrito"),
            e("🫔", "tamale"),
            e("🥙", "pita"),
            e("🧆", "falafel"),
            e("🥚", "egg"),
            e("🍳", "cooking", "fried", "egg"),
            e("🥘", "pan", "food"),
            e("🍲", "pot", "stew"),
            e("🫕", "fondue"),
            e("🥣", "cereal", "bowl"),
            e("🥗", "salad"),
            e("🍿", "popcorn"),
            e("🧈", "butter"),
            e("🧂", "salt"),
            e("🥫", "canned", "food"),
            e("🍱", "bento", "box"),
            e("🍘", "rice", "cracker"),
            e("🍙", "rice", "ball"),
            e("🍚", "rice"),
            e("🍛", "curry"),
            e("🍜", "noodles", "ramen"),
            e("🍝", "spaghetti", "pasta"),
            e("🍠", "sweet", "potato"),
            e("🍢", "oden"),
            e("🍣", "sushi"),
            e("🍤", "shrimp", "fried"),
            e("🍥", "fish", "cake"),
            e("🥮", "moon", "cake"),
            e("🍡", "dango"),
            e("🥟", "dumpling"),
            e("🥠", "fortune", "cookie"),
            e("🥡", "takeout"),
            e("🦀", "crab"),
            e("🦞", "lobster"),
            e("🦐", "shrimp"),
            e("🦑", "squid"),
            e("🦪", "oyster"),
            e("🍦", "ice", "cream"),
            e("🍧", "shaved", "ice"),
            e("🍨", "ice", "cream", "sundae"),
            e("🍩", "donut", "doughnut"),
            e("🍪", "cookie"),
            e("🎂", "birthday", "cake"),
            e("🍰", "cake", "shortcake"),
            e("🧁", "cupcake"),
            e("🥧", "pie"),
            e("🍫", "chocolate"),
            e("🍬", "candy"),
            e("🍭", "lollipop"),
            e("🍮", "custard", "pudding"),
            e("🍯", "honey"),
            e("🍼", "baby", "bottle"),
            e("🥛", "milk"),
            e("☕", "coffee", "tea"),
            e("🫖", "teapot"),
            e("🍵", "tea"),
            e("🍶", "sake"),
            e("🍾", "champagne"),
            e("🍷", "wine"),
            e("🍸", "cocktail", "martini"),
            e("🍹", "tropical", "drink"),
            e("🍺", "beer"),
            e("🍻", "beers", "cheers"),
            e("🥂", "clinking", "glasses"),
            e("🥃", "whisky", "tumbler"),
            e("🫗", "pouring", "liquid"),
            e("🥤", "cup", "straw"),
            e("🧋", "bubble", "tea"),
            e("🧃", "juice", "box"),
            e("🧉", "mate"),
            e("🧊", "ice", "cube"),
        ),
    )

    private fun travel() = EmojiCategory(
        name = "Travel & Places",
        icon = "✈️",
        emojis =
        listOf(
            e("🚗", "car", "automobile"),
            e("🚕", "taxi"),
            e("🚙", "suv"),
            e("🚌", "bus"),
            e("🚎", "trolleybus"),
            e("🏎️", "racing", "car"),
            e("🚓", "police", "car"),
            e("🚑", "ambulance"),
            e("🚒", "fire", "truck"),
            e("🚐", "minibus"),
            e("🛻", "pickup", "truck"),
            e("🚚", "truck"),
            e("🚛", "articulated", "lorry"),
            e("🚜", "tractor"),
            e("🛵", "motor", "scooter"),
            e("🏍️", "motorcycle"),
            e("🚲", "bicycle", "bike"),
            e("🛴", "kick", "scooter"),
            e("🛹", "skateboard"),
            e("🛼", "roller", "skate"),
            e("🚁", "helicopter"),
            e("✈️", "airplane"),
            e("🛩️", "small", "airplane"),
            e("🛫", "departure"),
            e("🛬", "arrival"),
            e("🪂", "parachute"),
            e("💺", "seat"),
            e("🚀", "rocket"),
            e("🛸", "ufo", "flying", "saucer"),
            e("🚁", "helicopter"),
            e("⛵", "sailboat"),
            e("🚤", "speedboat"),
            e("🛥️", "motor", "boat"),
            e("🛳️", "passenger", "ship"),
            e("⛴️", "ferry"),
            e("🚢", "ship"),
            e("⚓", "anchor"),
            e("🛟", "ring", "buoy"),
            e("⛽", "fuel", "gas"),
            e("🚧", "construction"),
            e("🚦", "traffic", "light"),
            e("🚥", "traffic", "signal"),
            e("🗺️", "world", "map"),
            e("🗿", "moai", "statue"),
            e("🗽", "statue", "liberty"),
            e("🗼", "tokyo", "tower"),
            e("🏰", "castle"),
            e("🏯", "japanese", "castle"),
            e("🏟️", "stadium"),
            e("🎡", "ferris", "wheel"),
            e("🎢", "roller", "coaster"),
            e("🎠", "carousel"),
            e("⛲", "fountain"),
            e("⛱️", "umbrella", "beach"),
            e("🏖️", "beach"),
            e("🏝️", "island"),
            e("🏜️", "desert"),
            e("🌋", "volcano"),
            e("⛰️", "mountain"),
            e("🏔️", "snow", "mountain"),
            e("🗻", "mount", "fuji"),
            e("🏕️", "camping"),
            e("⛺", "tent"),
            e("🛖", "hut"),
            e("🏠", "house"),
            e("🏡", "garden", "house"),
            e("🏢", "office", "building"),
            e("🏣", "post", "office"),
            e("🏤", "european", "post"),
            e("🏥", "hospital"),
            e("🏦", "bank"),
            e("🏨", "hotel"),
            e("🏩", "love", "hotel"),
            e("🏪", "convenience", "store"),
            e("🏫", "school"),
            e("🏬", "department", "store"),
            e("🏭", "factory"),
            e("🏗️", "construction", "building"),
            e("🧱", "brick"),
            e("🪨", "rock"),
            e("🪵", "wood"),
            e("🛤️", "railway", "track"),
            e("🛣️", "motorway"),
            e("🌅", "sunrise"),
            e("🌄", "sunrise", "mountains"),
            e("🌠", "shooting", "star"),
            e("🎇", "sparkler"),
            e("🎆", "fireworks"),
            e("🌇", "sunset", "city"),
            e("🌆", "cityscape", "dusk"),
            e("🏙️", "cityscape"),
            e("🌃", "night", "stars"),
            e("🌌", "milky", "way"),
            e("🌉", "bridge", "night"),
            e("🌁", "foggy"),
        ),
    )

    private fun activities() = EmojiCategory(
        name = "Activities",
        icon = "⚽",
        emojis =
        listOf(
            e("⚽", "soccer"),
            e("🏀", "basketball"),
            e("🏈", "football"),
            e("⚾", "baseball"),
            e("🥎", "softball"),
            e("🎾", "tennis"),
            e("🏐", "volleyball"),
            e("🏉", "rugby"),
            e("🥏", "frisbee"),
            e("🎱", "pool", "billiards"),
            e("🪀", "yoyo"),
            e("🏓", "ping", "pong"),
            e("🏸", "badminton"),
            e("🏒", "ice", "hockey"),
            e("🏑", "field", "hockey"),
            e("🥍", "lacrosse"),
            e("🏏", "cricket"),
            e("🪃", "boomerang"),
            e("🥅", "goal", "net"),
            e("⛳", "golf"),
            e("🪁", "kite"),
            e("🏹", "archery"),
            e("🎣", "fishing"),
            e("🤿", "diving"),
            e("🥊", "boxing"),
            e("🥋", "martial", "arts"),
            e("🎽", "running", "shirt"),
            e("🛹", "skateboard"),
            e("🛼", "roller", "skate"),
            e("🛷", "sled"),
            e("⛸️", "ice", "skate"),
            e("🥌", "curling"),
            e("🎿", "skiing"),
            e("⛷️", "skier"),
            e("🏂", "snowboard"),
            e("🪂", "parachute"),
            e("🏋️", "weightlifting"),
            e("🤺", "fencing"),
            e("🤸", "cartwheel"),
            e("🤼", "wrestling"),
            e("🤽", "water", "polo"),
            e("🤾", "handball"),
            e("🏌️", "golf"),
            e("🏇", "horse", "racing"),
            e("🧘", "yoga", "meditation"),
            e("🏄", "surfing"),
            e("🏊", "swimming"),
            e("🚣", "rowing"),
            e("🧗", "climbing"),
            e("🚵", "mountain", "biking"),
            e("🚴", "biking"),
            e("🏆", "trophy"),
            e("🥇", "gold", "medal"),
            e("🥈", "silver", "medal"),
            e("🥉", "bronze", "medal"),
            e("🏅", "medal"),
            e("🎖️", "military", "medal"),
            e("🎗️", "reminder", "ribbon"),
            e("🎪", "circus", "tent"),
            e("🤹", "juggling"),
            e("🎭", "performing", "arts"),
            e("🩰", "ballet"),
            e("🎨", "art", "palette"),
            e("🎬", "clapper", "movie"),
            e("🎤", "microphone", "karaoke"),
            e("🎧", "headphone"),
            e("🎼", "musical", "score"),
            e("🎹", "piano"),
            e("🥁", "drum"),
            e("🪘", "long", "drum"),
            e("🎷", "saxophone"),
            e("🎺", "trumpet"),
            e("🪗", "accordion"),
            e("🎸", "guitar"),
            e("🪕", "banjo"),
            e("🎻", "violin"),
            e("🎲", "dice", "game"),
            e("♟️", "chess"),
            e("🎯", "dart", "bullseye"),
            e("🎳", "bowling"),
            e("🎮", "video", "game"),
            e("🕹️", "joystick"),
            e("🎰", "slot", "machine"),
            e("🧩", "puzzle"),
        ),
    )

    private fun objects() = EmojiCategory(
        name = "Objects",
        icon = "💡",
        emojis =
        listOf(
            e("⌚", "watch"),
            e("📱", "phone", "mobile"),
            e("📲", "call", "phone"),
            e("💻", "laptop", "computer"),
            e("⌨️", "keyboard"),
            e("🖥️", "desktop", "computer"),
            e("🖨️", "printer"),
            e("🖱️", "mouse"),
            e("🖲️", "trackball"),
            e("💾", "floppy", "disk"),
            e("💿", "cd"),
            e("📀", "dvd"),
            e("🎥", "movie", "camera"),
            e("🎞️", "film"),
            e("📽️", "projector"),
            e("📺", "tv", "television"),
            e("📷", "camera"),
            e("📸", "camera", "flash"),
            e("📹", "video", "camera"),
            e("📼", "vhs"),
            e("🔍", "magnify", "search"),
            e("🔎", "magnify", "right"),
            e("🕯️", "candle"),
            e("💡", "bulb", "idea"),
            e("🔦", "flashlight"),
            e("🏮", "lantern"),
            e("🪔", "diya", "lamp"),
            e("📔", "notebook"),
            e("📕", "book", "closed"),
            e("📖", "book", "open"),
            e("📗", "green", "book"),
            e("📘", "blue", "book"),
            e("📙", "orange", "book"),
            e("📚", "books"),
            e("📓", "notebook"),
            e("📒", "ledger"),
            e("📃", "page", "curl"),
            e("📜", "scroll"),
            e("📄", "document"),
            e("📰", "newspaper"),
            e("🗞️", "rolled", "newspaper"),
            e("📑", "bookmark", "tabs"),
            e("🔖", "bookmark"),
            e("🏷️", "label", "tag"),
            e("💰", "money", "bag"),
            e("🪙", "coin"),
            e("💴", "yen"),
            e("💵", "dollar"),
            e("💶", "euro"),
            e("💷", "pound"),
            e("💸", "money", "wings"),
            e("💳", "credit", "card"),
            e("🧾", "receipt"),
            e("✉️", "envelope", "mail"),
            e("📧", "email"),
            e("📨", "incoming", "mail"),
            e("📩", "envelope", "arrow"),
            e("📤", "outbox"),
            e("📥", "inbox"),
            e("📦", "package"),
            e("📫", "mailbox"),
            e("📪", "mailbox", "empty"),
            e("📬", "mailbox", "flag"),
            e("📭", "mailbox", "empty"),
            e("📮", "postbox"),
            e("✏️", "pencil"),
            e("✒️", "pen", "nib"),
            e("🖊️", "pen"),
            e("🖋️", "fountain", "pen"),
            e("🖌️", "paintbrush"),
            e("🖍️", "crayon"),
            e("📝", "memo", "note"),
            e("📁", "folder"),
            e("📂", "folder", "open"),
            e("🗂️", "card", "index"),
            e("📅", "calendar"),
            e("📆", "calendar", "tear"),
            e("🗒️", "spiral", "notepad"),
            e("🗓️", "spiral", "calendar"),
            e("📇", "card", "index"),
            e("📈", "chart", "up"),
            e("📉", "chart", "down"),
            e("📊", "bar", "chart"),
            e("📋", "clipboard"),
            e("📌", "pushpin"),
            e("📍", "pin"),
            e("📎", "paperclip"),
            e("🖇️", "paperclips"),
            e("📏", "ruler"),
            e("📐", "triangular", "ruler"),
            e("✂️", "scissors"),
            e("🗃️", "card", "file"),
            e("🗄️", "file", "cabinet"),
            e("🗑️", "trash"),
            e("🔒", "lock"),
            e("🔓", "unlock"),
            e("🔏", "lock", "pen"),
            e("🔐", "lock", "key"),
            e("🔑", "key"),
            e("🗝️", "old", "key"),
            e("🔨", "hammer"),
            e("🪓", "axe"),
            e("⛏️", "pick"),
            e("⚒️", "hammer", "pick"),
            e("🛠️", "tools"),
            e("🗡️", "dagger"),
            e("⚔️", "swords"),
            e("💣", "bomb"),
            e("🪃", "boomerang"),
            e("🏹", "bow", "arrow"),
            e("🛡️", "shield"),
            e("🪚", "saw"),
            e("🔧", "wrench"),
            e("🪛", "screwdriver"),
            e("🔩", "nut", "bolt"),
            e("⚙️", "gear"),
            e("🗜️", "clamp"),
            e("⚖️", "balance", "scale"),
            e("🦯", "probing", "cane"),
            e("🔗", "link", "chain"),
            e("⛓️", "chains"),
            e("🪝", "hook"),
            e("🧰", "toolbox"),
            e("🧲", "magnet"),
            e("🪜", "ladder"),
            e("🧪", "test", "tube"),
            e("🧫", "petri", "dish"),
            e("🧬", "dna"),
            e("🔬", "microscope"),
            e("🔭", "telescope"),
            e("📡", "satellite", "antenna", "radio"),
            e("📻", "radio"),
            e("🔋", "battery"),
            e("🪫", "low", "battery"),
            e("🔌", "plug", "electric"),
            e("🧭", "compass"),
        ),
    )

    private fun symbols() = EmojiCategory(
        name = "Symbols",
        icon = "🔣",
        emojis =
        listOf(
            e("❤️", "red", "heart"),
            e("🧡", "orange", "heart"),
            e("💛", "yellow", "heart"),
            e("💚", "green", "heart"),
            e("💙", "blue", "heart"),
            e("💜", "purple", "heart"),
            e("🖤", "black", "heart"),
            e("🤍", "white", "heart"),
            e("🤎", "brown", "heart"),
            e("💔", "broken", "heart"),
            e("❣️", "heart", "exclamation"),
            e("💕", "two", "hearts"),
            e("💞", "revolving", "hearts"),
            e("💓", "heartbeat"),
            e("💗", "growing", "heart"),
            e("💖", "sparkling", "heart"),
            e("💘", "cupid"),
            e("💝", "ribbon", "heart"),
            e("💟", "heart", "decoration"),
            e("☮️", "peace"),
            e("✝️", "cross"),
            e("☪️", "star", "crescent"),
            e("🕉️", "om"),
            e("☸️", "wheel", "dharma"),
            e("✡️", "star", "david"),
            e("🔯", "six", "pointed", "star"),
            e("🕎", "menorah"),
            e("☯️", "yin", "yang"),
            e("☦️", "orthodox", "cross"),
            e("🛐", "worship"),
            e("⛎", "ophiuchus"),
            e("♈", "aries"),
            e("♉", "taurus"),
            e("♊", "gemini"),
            e("♋", "cancer"),
            e("♌", "leo"),
            e("♍", "virgo"),
            e("♎", "libra"),
            e("♏", "scorpio"),
            e("♐", "sagittarius"),
            e("♑", "capricorn"),
            e("♒", "aquarius"),
            e("♓", "pisces"),
            e("🆔", "id"),
            e("⚛️", "atom"),
            e("🉑", "accept"),
            e("☢️", "radioactive"),
            e("☣️", "biohazard"),
            e("📴", "phone", "off"),
            e("📳", "vibration"),
            e("🈶", "ideograph"),
            e("🈚", "ideograph"),
            e("🈸", "application"),
            e("🈺", "open"),
            e("🈷️", "monthly"),
            e("✴️", "eight", "pointed", "star"),
            e("🆚", "versus"),
            e("💮", "white", "flower"),
            e("🉐", "bargain"),
            e("㊙️", "secret"),
            e("㊗️", "congratulations"),
            e("🈴", "passing"),
            e("🈵", "full"),
            e("🈹", "discount"),
            e("🈲", "prohibited"),
            e("🅰️", "a", "blood"),
            e("🅱️", "b", "blood"),
            e("🆎", "ab", "blood"),
            e("🆑", "cl"),
            e("🅾️", "o", "blood"),
            e("🆘", "sos"),
            e("❌", "x", "cross"),
            e("⭕", "circle"),
            e("🛑", "stop"),
            e("⛔", "prohibited"),
            e("📛", "name", "badge"),
            e("🚫", "prohibited"),
            e("💯", "hundred"),
            e("💢", "anger"),
            e("♨️", "hot", "springs"),
            e("🚷", "no", "pedestrians"),
            e("🚯", "no", "littering"),
            e("🚳", "no", "bicycles"),
            e("🚱", "non", "potable"),
            e("🔞", "eighteen"),
            e("📵", "no", "phones"),
            e("🚭", "no", "smoking"),
            e("❗", "exclamation"),
            e("❕", "exclamation"),
            e("❓", "question"),
            e("❔", "question"),
            e("‼️", "double", "exclamation"),
            e("⁉️", "exclamation", "question"),
            e("🔅", "dim"),
            e("🔆", "bright"),
            e("〽️", "part", "alternation"),
            e("⚠️", "warning"),
            e("🚸", "children", "crossing"),
            e("🔱", "trident"),
            e("⚜️", "fleur", "de", "lis"),
            e("🔰", "beginner"),
            e("♻️", "recycle"),
            e("✅", "check", "mark"),
            e("🈯", "reserved"),
            e("💹", "chart"),
            e("❇️", "sparkle"),
            e("✳️", "eight", "spoked"),
            e("❎", "cross", "mark"),
            e("🌐", "globe", "meridians"),
            e("💠", "diamond", "dot"),
            e("Ⓜ️", "m", "circled"),
            e("🌀", "cyclone"),
            e("💤", "zzz", "sleep"),
            e("🏧", "atm"),
            e("🚾", "wc"),
            e("♿", "wheelchair"),
            e("🅿️", "parking"),
            e("🛗", "elevator"),
            e("🈳", "vacant"),
            e("🈂️", "service"),
            e("🛂", "passport", "control"),
            e("🛃", "customs"),
            e("🛄", "baggage", "claim"),
            e("🛅", "left", "luggage"),
            e("🔣", "symbols"),
            e("ℹ️", "info"),
            e("🔤", "abc"),
            e("🔡", "abcd"),
            e("🔠", "abcd", "upper"),
            e("🆖", "ng"),
            e("🆗", "ok"),
            e("🆙", "up"),
            e("🆒", "cool"),
            e("🆕", "new"),
            e("🆓", "free"),
            e("0️⃣", "zero"),
            e("1️⃣", "one"),
            e("2️⃣", "two"),
            e("3️⃣", "three"),
            e("4️⃣", "four"),
            e("5️⃣", "five"),
            e("6️⃣", "six"),
            e("7️⃣", "seven"),
            e("8️⃣", "eight"),
            e("9️⃣", "nine"),
            e("🔟", "ten"),
            e("🔢", "numbers"),
            e("#️⃣", "hash"),
            e("*️⃣", "asterisk"),
            e("⏏️", "eject"),
            e("▶️", "play"),
            e("⏸️", "pause"),
            e("⏯️", "play", "pause"),
            e("⏹️", "stop"),
            e("⏺️", "record"),
            e("⏭️", "next", "track"),
            e("⏮️", "previous", "track"),
            e("⏩", "fast", "forward"),
            e("⏪", "rewind"),
            e("⏫", "fast", "up"),
            e("⏬", "fast", "down"),
            e("◀️", "reverse"),
            e("🔼", "up", "triangle"),
            e("🔽", "down", "triangle"),
            e("➡️", "right", "arrow"),
            e("⬅️", "left", "arrow"),
            e("⬆️", "up", "arrow"),
            e("⬇️", "down", "arrow"),
            e("↗️", "upper", "right"),
            e("↘️", "lower", "right"),
            e("↙️", "lower", "left"),
            e("↖️", "upper", "left"),
            e("↕️", "up", "down"),
            e("↔️", "left", "right"),
            e("↩️", "leftwards"),
            e("↪️", "rightwards"),
            e("⤴️", "right", "curve"),
            e("⤵️", "left", "curve"),
            e("🔀", "shuffle"),
            e("🔁", "repeat"),
            e("🔂", "repeat", "one"),
            e("🔄", "counterclockwise"),
            e("🔃", "clockwise"),
            e("🎵", "musical", "note"),
            e("🎶", "notes", "music"),
            e("➕", "plus"),
            e("➖", "minus"),
            e("➗", "divide"),
            e("✖️", "multiply"),
            e("🟰", "equals"),
            e("♾️", "infinity"),
            e("💲", "dollar", "sign"),
            e("💱", "currency", "exchange"),
            e("™️", "trademark"),
            e("©️", "copyright"),
            e("®️", "registered"),
            e("〰️", "wavy", "dash"),
            e("➰", "curly", "loop"),
            e("➿", "double", "curly"),
            e("🔚", "end"),
            e("🔙", "back"),
            e("🔛", "on"),
            e("🔝", "top"),
            e("🔜", "soon"),
            e("✔️", "check"),
            e("☑️", "ballot", "check"),
            e("🔘", "radio", "button"),
            e("🔴", "red", "circle"),
            e("🟠", "orange", "circle"),
            e("🟡", "yellow", "circle"),
            e("🟢", "green", "circle"),
            e("🔵", "blue", "circle"),
            e("🟣", "purple", "circle"),
            e("🟤", "brown", "circle"),
            e("⚫", "black", "circle"),
            e("⚪", "white", "circle"),
            e("🟥", "red", "square"),
            e("🟧", "orange", "square"),
            e("🟨", "yellow", "square"),
            e("🟩", "green", "square"),
            e("🟦", "blue", "square"),
            e("🟪", "purple", "square"),
            e("🟫", "brown", "square"),
            e("⬛", "black", "large", "square"),
            e("⬜", "white", "large", "square"),
            e("◼️", "black", "medium", "square"),
            e("◻️", "white", "medium", "square"),
            e("◾", "black", "small", "square"),
            e("◽", "white", "small", "square"),
            e("▪️", "black", "smallest", "square"),
            e("▫️", "white", "smallest", "square"),
            e("🔶", "large", "orange", "diamond"),
            e("🔷", "large", "blue", "diamond"),
            e("🔸", "small", "orange", "diamond"),
            e("🔹", "small", "blue", "diamond"),
            e("🔺", "red", "triangle", "up"),
            e("🔻", "red", "triangle", "down"),
            e("💠", "diamond", "shape"),
            e("🔘", "radio"),
            e("🔳", "white", "square"),
            e("🔲", "black", "square"),
        ),
    )

    private fun flags() = EmojiCategory(
        name = "Flags",
        icon = "🏁",
        emojis =
        listOf(
            e("🏁", "checkered", "flag"),
            e("🚩", "triangular", "flag"),
            e("🎌", "crossed", "flags"),
            e("🏴", "black", "flag"),
            e("🏳️", "white", "flag"),
            e("🏳️‍🌈", "rainbow", "flag", "pride"),
            e("🏳️‍⚧️", "transgender", "flag"),
            e("🏴‍☠️", "pirate", "flag"),
            e("🇺🇸", "us", "usa", "america"),
            e("🇬🇧", "uk", "britain"),
            e("🇨🇦", "canada"),
            e("🇦🇺", "australia"),
            e("🇩🇪", "germany"),
            e("🇫🇷", "france"),
            e("🇪🇸", "spain"),
            e("🇮🇹", "italy"),
            e("🇯🇵", "japan"),
            e("🇰🇷", "korea", "south"),
            e("🇨🇳", "china"),
            e("🇮🇳", "india"),
            e("🇧🇷", "brazil"),
            e("🇲🇽", "mexico"),
            e("🇷🇺", "russia"),
            e("🇿🇦", "south", "africa"),
            e("🇳🇬", "nigeria"),
            e("🇪🇬", "egypt"),
            e("🇸🇦", "saudi", "arabia"),
            e("🇦🇪", "uae", "emirates"),
            e("🇮🇱", "israel"),
            e("🇹🇷", "turkey"),
            e("🇳🇱", "netherlands"),
            e("🇧🇪", "belgium"),
            e("🇨🇭", "switzerland"),
            e("🇦🇹", "austria"),
            e("🇸🇪", "sweden"),
            e("🇳🇴", "norway"),
            e("🇩🇰", "denmark"),
            e("🇫🇮", "finland"),
            e("🇵🇱", "poland"),
            e("🇵🇹", "portugal"),
            e("🇬🇷", "greece"),
            e("🇮🇪", "ireland"),
            e("🇳🇿", "new", "zealand"),
            e("🇸🇬", "singapore"),
            e("🇹🇭", "thailand"),
            e("🇻🇳", "vietnam"),
            e("🇮🇩", "indonesia"),
            e("🇵🇭", "philippines"),
            e("🇲🇾", "malaysia"),
            e("🇦🇷", "argentina"),
            e("🇨🇴", "colombia"),
            e("🇨🇱", "chile"),
            e("🇵🇪", "peru"),
            e("🇺🇦", "ukraine"),
            e("🇷🇴", "romania"),
            e("🇭🇺", "hungary"),
            e("🇨🇿", "czech"),
        ),
    )
}
