/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.feature.settings.navigation

// The jvmAndroid actual reads a plain JVM classpath resource (Class.getResource) generated by the
// meshtastic.aboutlibraries convention plugin into androidApp's/desktopApp's own src/main/resources -- a mechanism
// that doesn't exist on wasmJs (no java.lang.Class) and, more fundamentally, isn't generated for any web module yet
// (no webApp exists). A real fix needs that plugin's output routed through Compose Multiplatform resources
// (proven wasmJs-safe by core:resources) once a webApp module exists to apply it -- same "not yet, no host to wire
// it into" posture as core:service's NoopTakServerIntegration. Matches iOS's own TODO stub in the meantime.
actual fun getAboutLibrariesJson(): String = ""
