/* Generated by write_pilot_file() Octave function */

#define NSYMROW      4   /* number of data symbols on each row (i.e. each carrier) */
#define NS           4   /* number of data symbols between pilots                   */
#define NPILOTSFRAME 2   /* number of pilot symbols on each row                     */
#define PILOTS_NC    7   /* number of carriers                                      */

#define NSYMROWPILOT 6   /* length of row after pilots inserted                     */

