/*
  FILE....: H_1024_2048_4f.h

  Static arrays for LDPC codec H_1024_2048_4f, generated by ldpc_gen_c_h_file.m.
*/

#define H_1024_2048_4f_NUMBERPARITYBITS 1024
#define H_1024_2048_4f_MAX_ROW_WEIGHT 12
#define H_1024_2048_4f_CODELENGTH 2048
#define H_1024_2048_4f_NUMBERROWSHCOLS 1024
#define H_1024_2048_4f_MAX_COL_WEIGHT 54
#define H_1024_2048_4f_DEC_TYPE 0
#define H_1024_2048_4f_MAX_ITER 100

extern const uint16_t H_1024_2048_4f_H_rows[];
extern const uint16_t H_1024_2048_4f_H_cols[];
