/*
  FILE....: H_128_256_5.h

  Static arrays for LDPC codec H_128_256_5, generated by ldpc_gen_c_h_file.m.
*/

#define H_128_256_5_NUMBERPARITYBITS 128
#define H_128_256_5_MAX_ROW_WEIGHT 5
#define H_128_256_5_CODELENGTH 256
#define H_128_256_5_NUMBERROWSHCOLS 128
#define H_128_256_5_MAX_COL_WEIGHT 5
#define H_128_256_5_DEC_TYPE 0
#define H_128_256_5_MAX_ITER 100

extern const uint16_t H_128_256_5_H_rows[];
extern const uint16_t H_128_256_5_H_cols[];
extern const float H_128_256_5_input[];
extern const char H_128_256_5_detected_data[];

