/*
  FILE....: H_16200_9720.h

  Static arrays for LDPC codec H_16200_9720, generated by ldpc_gen_c_h_file.m.
*/

#define H_16200_9720_NUMBERPARITYBITS 6480
#define H_16200_9720_MAX_ROW_WEIGHT 9
#define H_16200_9720_CODELENGTH 16200
#define H_16200_9720_NUMBERROWSHCOLS 9720
#define H_16200_9720_MAX_COL_WEIGHT 12
#define H_16200_9720_DEC_TYPE 0
#define H_16200_9720_MAX_ITER 100

extern const uint16_t H_16200_9720_H_rows[];
extern const uint16_t H_16200_9720_H_cols[];
