/*
  FILE....: H_256_512_4.h

  Static arrays for LDPC codec H_256_512_4, generated by ldpc_gen_c_h_file.m.
*/

#define H_256_512_4_NUMBERPARITYBITS 256
#define H_256_512_4_MAX_ROW_WEIGHT 4
#define H_256_512_4_CODELENGTH 512
#define H_256_512_4_NUMBERROWSHCOLS 256
#define H_256_512_4_MAX_COL_WEIGHT 4
#define H_256_512_4_DEC_TYPE 0
#define H_256_512_4_MAX_ITER 100

extern const uint16_t H_256_512_4_H_rows[];
extern const uint16_t H_256_512_4_H_cols[];
extern const float H_256_512_4_input[];
extern const char H_256_512_4_detected_data[];

