/*
  FILE....: H_256_768_22.h

  Static arrays for LDPC codec H_256_768_22, generated by ldpc_gen_c_h_file.m.
*/

#define H_256_768_22_NUMBERPARITYBITS 512
#define H_256_768_22_MAX_ROW_WEIGHT 2
#define H_256_768_22_CODELENGTH 768
#define H_256_768_22_NUMBERROWSHCOLS 256
#define H_256_768_22_MAX_COL_WEIGHT 4
#define H_256_768_22_DEC_TYPE 0
#define H_256_768_22_MAX_ITER 100

extern const uint16_t H_256_768_22_H_rows[];
extern const uint16_t H_256_768_22_H_cols[];
extern const float H_256_768_22_input[];
extern const char H_256_768_22_detected_data[];

