/*
  FILE....: H_4096_8192_3d.h

  Static arrays for LDPC codec H_4096_8192_3d, generated by ldpc_gen_c_h_file.m.
*/

#define H_4096_8192_3d_NUMBERPARITYBITS 4096
#define H_4096_8192_3d_MAX_ROW_WEIGHT 9
#define H_4096_8192_3d_CODELENGTH 8192
#define H_4096_8192_3d_NUMBERROWSHCOLS 4096
#define H_4096_8192_3d_MAX_COL_WEIGHT 13
#define H_4096_8192_3d_DEC_TYPE 0
#define H_4096_8192_3d_MAX_ITER 100

extern const uint16_t H_4096_8192_3d_H_rows[];
extern const uint16_t H_4096_8192_3d_H_cols[];
extern const float H_4096_8192_3d_input[];
extern const char H_4096_8192_3d_detected_data[];

