/*
  FILE....: HRA_56_56.h

  Static arrays for LDPC codec HRA_56_56, generated by ldpc_gen_c_h_file.m.
*/

#define HRA_56_56_NUMBERPARITYBITS 56
#define HRA_56_56_MAX_ROW_WEIGHT 3
#define HRA_56_56_CODELENGTH 112
#define HRA_56_56_NUMBERROWSHCOLS 56
#define HRA_56_56_MAX_COL_WEIGHT 3
#define HRA_56_56_DEC_TYPE 0
#define HRA_56_56_MAX_ITER 100

extern const uint16_t HRA_56_56_H_rows[];
extern const uint16_t HRA_56_56_H_cols[];
extern const float HRA_56_56_input[];
extern const char HRA_56_56_detected_data[];

