/*
  FILE....: HRAa_1536_512.h

  Static arrays for LDPC codec HRAa_1536_512, generated by ldpc_gen_c_h_file.m.
*/

#define HRAa_1536_512_NUMBERPARITYBITS 512
#define HRAa_1536_512_MAX_ROW_WEIGHT 12
#define HRAa_1536_512_CODELENGTH 2048
#define HRAa_1536_512_NUMBERROWSHCOLS 1536
#define HRAa_1536_512_MAX_COL_WEIGHT 4
#define HRAa_1536_512_DEC_TYPE 0
#define HRAa_1536_512_MAX_ITER 100

extern const uint16_t HRAa_1536_512_H_rows[];
extern const uint16_t HRAa_1536_512_H_cols[];
extern const float HRAa_1536_512_input[];
extern const char HRAa_1536_512_detected_data[];

