/*
  FILE....: HRAb_396_504.h

  Static arrays for LDPC codec HRAb_396_504, generated by ldpc_gen_c_h_file.m.
*/

#define HRAb_396_504_NUMBERPARITYBITS 108
#define HRAb_396_504_MAX_ROW_WEIGHT 12
#define HRAb_396_504_CODELENGTH 504
#define HRAb_396_504_NUMBERROWSHCOLS 396
#define HRAb_396_504_MAX_COL_WEIGHT 7
#define HRAb_396_504_DEC_TYPE 0
#define HRAb_396_504_MAX_ITER 100

extern const uint16_t HRAb_396_504_H_rows[];
extern const uint16_t HRAb_396_504_H_cols[];
extern const float HRAb_396_504_input[];
extern const char HRAb_396_504_detected_data[];

