#!/bin/bash

list_descendants ()
{
  local children=$(ps -o pid= --ppid "$1")

  for pid in $children
  do
    list_descendants "$pid"
  done

  echo $children
}

kill $(list_descendants $(pidof -x run_stm32_tst))
