#!/bin/bash
#
# run_all_codec2_tests

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

declare -i Fails=0

run_stm32_tst tst_codec2_enc 1300 "$@"  || Fails+=1
run_stm32_tst tst_codec2_enc 700C "$@"        || Fails+=1

run_stm32_tst tst_codec2_dec 1300 "$@" || Fails+=1
run_stm32_tst tst_codec2_dec 700C "$@"        || Fails+=1

if (( $Fails == 0 )); then
    echo -e "\nAll Codec2 Tests PASSED"
else
    echo -e "\n$Fails Codec2 Tests FAILED!"
fi

exit $Fails

# vi:set ts=4 et sts=4:
