#!/bin/bash
#
# tst_ldpc_enc_setup
#
# Setup input and reference data for one of several versions of this test.

# Find the scripts directory
SCRIPTS="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

# Setup common variables
source $SCRIPTS/run_tests_common.sh

# RUN_DIR - Directory where test will be run
RUN_DIR="${UNITTEST_BASE}/test_run/${FULL_TEST_NAME}"

# Call common setup function to make the directory
setup_common "${RUN_DIR}"

# Change to test directory
cd "${RUN_DIR}"


#####################################################################
## Test SETUP actions:

#case "${TEST_OPT}" in
#
#    plain )
#    	# Config is <unused>, <unused>, <ldpc_en>, <unused> <profile>
#    	echo "00000000" > stm_cfg.txt
	ofdm_get_test_bits --out stm_in.raw --frames 6 --verbose \
	    > setup.log 2>&1
    	ldpc_enc stm_in.raw ref_out.raw --code HRA_112_112 \
	    > ref_gen.log 2>&1
#	;;
#
#    esac

exit 0
