-keep class org.meshtastic.proto.MeshProtos$DeviceMetadata
-keep class org.meshtastic.proto.MeshProtos$FromRadio
-keep class org.meshtastic.proto.MeshProtos$Position
-keep class org.meshtastic.proto.MeshProtos$User
-keep class org.meshtastic.proto.PaxcountProtos$Paxcount
-keep class org.meshtastic.proto.TelemetryProtos$Telemetry
