-keep class org.meshtastic.proto.DeviceMetadata
-keep class org.meshtastic.proto.FromRadio
-keep class org.meshtastic.proto.Position
-keep class org.meshtastic.proto.User
-keep class org.meshtastic.proto.Paxcount
-keep class org.meshtastic.proto.Telemetry
