name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: [bug]
type: Bug
projects: [meshtastic/Meshtastic-Android]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com, discord username
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: A bug happened!
    validations:
      required: true
  - type: textarea
    id: app_version
    attributes:
      label: App Version
      description: What version of Meshtastic Android are you running?
      placeholder: 2.4.1
    validations:
      required: true
  - type: textarea
    id: phone
    attributes:
      label: Phone
      description: What phone/tablet and OS are you running it on?
      placeholder: Pixel 8a, Android 15
    validations:
      required: true
  - type: textarea
    id: radio
    attributes:
      label: Device
      description: Which meshtastic radio device are you connecting to?
      placeholder: heltec v3
    validations:
      required: true
  - type: textarea
    id: firmware
    attributes:
      label: Firmware
      description: Which meshtastic firmware is running on the device?
      placeholder: 2.4.1.394e0e1 Beta
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        Logs help us to diagnose and reproduce issues, particularly when they are unique to your setup.
        Depending on the issue, the following logs may be useful:
        - App logs: This will help with most issues.
            - Use logcat (with Android studio is simplest) and filter by com.geeksville.mesh
        - Mesh logs:  UI issues, communication issues etc.
            - ` App > Menu > Debug Panel > Export specific / export all `
        - Android logs: Potentially useful if the issue goes beyond the app (connections, network etc.)
            - Use logcat (with Android studio is simplest) and figure out what filters are needed to show us what is going wrong.
        - Firmware logs: Useful for all connection issues with nodes
          - These are piped to the USB serial port on the node, the most foolproof is to use the 'open serial' button on the web-flasher interface, and then save the output.
            - You need to be connecting to the node via Bluetooth or Network for this to work.
  - type: markdown
    attributes:
      value: |

        ### Relevant log output
        <details>

        <summary>Expand Logs ... </summary>
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
    attributes:
      value: |
        </details>
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://meshtastic.org/docs/legal/conduct/).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true