blank_issues_enabled: false
contact_links:
  - name: Meshtastic Android Discussions
    url: https://github.com/orgs/meshtastic/discussions/categories/android
    about: Please ask and answer questions here.
  - name: Meshtastic Website
    url: https://meshtastic.org/
    about: Docs and other ways to contact us here.


