name: Feature Request
description: File a request for new feature or functionality.
title: "[Feature Request]: "
labels: [enhancement]
projects: [meshtastic/Meshtastic-Android]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Please make sure you have done the following before submitting your feature request.
        Requests that do not meet these criteria will be closed.
        Links:  
          [**OPEN ISSUES**](https://github.com/meshtastic/Meshtastic-Android/issues)
          [**CLOSED ISSUES**](https://github.com/meshtastic/Meshtastic-Android/issues?q=is%3Aissue+is%3Aclosed)
          [Contribution Guidelines](https://github.com/meshtastic/Meshtastic-Android/blob/main/README.md#contributing)
      options:
        - label:
            I have used the search function for **OPEN ISSUES** to see if someone else has already submitted the same feature request.
          required: true
        - label: |
            I have **also** used the search function for **CLOSED ISSUES** to see if the feature was already implemented and is just waiting to be released, or if the feature was rejected.
          required: true
        - label: |
            I will describe the request with as much detail as possible.
          required: true
        - label: |
            This request contains only one single feature, **not** a list of multiple (related) features.
          required: true
        - label: |
            I have read and understood the **Contribution Guidelines**.
          required: true
        - label: |
            I agree to follow this project's Code of Conduct
          required: true
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com, discord username
    validations:
      required: false
  - type: textarea
    id: feature
    attributes:
      label: Feature or improvement you want
      description: Try to be as specific as possible. Please not only explain what the feature does, but also how.
  - type: textarea
    id: reason
    attributes:
      label: Why should this be added?
      description: |
        What problem does the feature solve? In what use-cases is the feature needed?
        Is this supported by the firmware? Please provide links to relevant firmware issues or PRs if applicable.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots / Drawings / Technical details
      description: If your request is about (or includes) changing or extending the UI, describe what the UI would look like and how the user would interact with it.