/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.schemastrings

/**
 * The Kotlin half of the sync: a lookup from an enum value to the resource holding its schema label, so a picker shows
 * the label every client shares instead of the constant's Kotlin name.
 *
 * The keys these build are [SchemaCatalog.keyFor]'s, so this file and `schema_strings.xml` cannot name a value
 * differently. What the lookup cannot do is fail at compile time: a resource that is not there reads as null, which is
 * why `SchemaEnumLabelsTest` walks every labelled constant.
 */
object EnumLabelsKt {

    /** One enum the schema labels: its proto path, the prefix its values share, and whether any value is described. */
    data class LabelledEnum(val path: String, val prefix: String, val hasDescriptions: Boolean)

    /**
     * The whole generated file. Spotless reformats it afterwards, so this is the input to the formatter rather than the
     * committed bytes - which is why `RepositorySyncTest` compares the branches it declares, not its text. The notice
     * sits below the imports because the licence-header step deletes anything between the header and `package`.
     */
    fun render(header: String, pin: String, enums: List<LabelledEnum>): String = buildString {
        append(header)
        append("package $PACKAGE\n\n")
        imports(enums).forEach { append("import ").append(it).append('\n') }
        append('\n').append(notice(pin)).append('\n')
        append(LABEL_DOC)
        append("@Suppress(\"CyclomaticComplexMethod\")\n")
        append("fun Enum<*>.schemaLabelRes(): StringResource? = when (this) {\n")
        enums.forEach { append(branch(it, "schemaLabel")) }
        append("    else -> null\n}\n")
        append(DESCRIPTION_DOC)
        append("@Suppress(\"CyclomaticComplexMethod\")\n")
        append("fun Enum<*>.schemaDescriptionRes(): StringResource? = when (this) {\n")
        enums.filter { it.hasDescriptions }.forEach { append(branch(it, "schemaDescription")) }
        append("    else -> null\n}\n")
        append(PREFIXES_DOC)
        append("val $PREFIXES: Set<String> =\n    setOf(\n")
        enums.forEach { append("        \"").append(it.prefix).append("\",\n") }
        append("    )\n")
        append(HELPER)
    }

    /**
     * One `when` branch. A branch that would not fit on a line is an error rather than a wrap: a wrapped branch makes
     * the formatter space out every other branch in the same `when`, and the fix belongs in the name, not here.
     */
    private fun branch(enum: LabelledEnum, function: String): String {
        val line = "    is ${enum.path} -> $function(\"${enum.prefix}\")"
        require(line.length <= MAX_LINE) { "branch for ${enum.path} is ${line.length} characters, over $MAX_LINE" }
        return "$line\n"
    }

    /** The name of the generated set, so the test and the renderer cannot disagree about it. */
    const val PREFIXES = "schemaEnumValuePrefixes"

    /** `"schema_lora_modempreset_",` as the committed file spells one entry of that set. */
    val prefixEntryPattern: Regex = Regex("""^\s{8}"(schema_[a-z0-9_]+_)",$""", RegexOption.MULTILINE)

    /** `is Config.DeviceConfig.Role -> ...`, as the committed file spells it, for the drift check. */
    val branchPattern: Regex =
        Regex("""^\s*is ([\w.]+) -> schema(Label|Description)\("([^"]+)"\)""", RegexOption.MULTILINE)

    /** `Config.DeviceConfig.Role` needs only `Config` imported; a top-level enum needs itself. */
    private fun imports(enums: List<LabelledEnum>): List<String> =
        (FIXED_IMPORTS + enums.map { "$PROTO_PACKAGE.${it.path.substringBefore('.')}" }).distinct().sorted()

    fun notice(pin: String): String =
        "// Generated by ./gradlew :schema-strings:sync from org.meshtastic:protobufs $pin.\n" +
            "// Do not edit: change the schema, then run sync."

    private const val MAX_LINE = 120
    private const val PACKAGE = "org.meshtastic.core.model"
    private const val PROTO_PACKAGE = "org.meshtastic.proto"

    private val FIXED_IMPORTS =
        listOf(
            "org.jetbrains.compose.resources.StringResource",
            "org.meshtastic.core.resources.Res",
            "org.meshtastic.core.resources.allStringResources",
        )

    private val LABEL_DOC =
        """
        |
        |/**
        | * The schema's label for this enum value, or null where the schema does not name it. A picker shows this in
        | * place of the constant's Kotlin name, and falls back to that name when it is null, so a value the schema has
        | * not reached still renders.
        | */
        |"""
            .trimMargin()

    private val PREFIXES_DOC =
        """
        |
        |/**
        | * The resource prefix every value of a labelled enum shares, one per enum. A consumer that has to tell an enum
        | * value's resource from a field's - settings search, which indexes fields and not the values they offer - reads
        | * this rather than keeping its own copy of the list.
        | */
        |"""
            .trimMargin()

    private val DESCRIPTION_DOC =
        """
        |
        |/** The schema's one-sentence explanation of this enum value, or null where it has none. */
        |"""
            .trimMargin()

    private val HELPER =
        """
        |
        |private fun Enum<*>.schemaLabel(prefix: String): StringResource? =
        |    Res.allStringResources[prefix + name.lowercase()]
        |
        |private fun Enum<*>.schemaDescription(prefix: String): StringResource? =
        |    Res.allStringResources[prefix + name.lowercase() + "_description"]
        |"""
            .trimMargin()
}
