/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.feature.settings.radio

import com.squareup.wire.WireField
import org.meshtastic.proto.FieldMetadataRegistry
import java.io.File
import java.util.zip.ZipFile
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * Every field the schema gives a label is either offered by a settings screen or named below with a reason. A field the
 * schema does not label cannot be rendered at all - there is no text for it - so it is never listed.
 *
 * What this pins is the schema side, which is where the change comes from: a newly annotated field upstream moves the
 * count and has to be given a control or a reason. It cannot prove a screen renders a field; android lays its screens
 * out by hand, so unlike Meshtastic-Apple's overlay there is no structure to read that from. The reasons below are a
 * review matter, the count is the ratchet.
 *
 * JVM-only: walking the generated messages needs `Class.forName` over the protobufs jar.
 */
class SchemaFieldCoverageTest {

    private enum class Reason {
        /** The field is one android has no control for, on a screen it otherwise renders. */
        NO_CONTROL,

        /** The whole module has no settings screen yet. */
        NO_SCREEN,
    }

    private val notOffered =
        mapOf(
            "Config.LoRaConfig.ignore_incoming" to Reason.NO_CONTROL,
            "ModuleConfig.TrafficManagementConfig.nodeinfo_direct_response_max_hops" to Reason.NO_SCREEN,
            "ModuleConfig.TrafficManagementConfig.position_min_interval_secs" to Reason.NO_SCREEN,
            "ModuleConfig.TrafficManagementConfig.rate_limit_max_packets" to Reason.NO_SCREEN,
            "ModuleConfig.TrafficManagementConfig.rate_limit_window_secs" to Reason.NO_SCREEN,
            "ModuleConfig.TrafficManagementConfig.unknown_packet_threshold" to Reason.NO_SCREEN,
        )

    /**
     * Every field the schema labels, as of the pin in `gradle/libs.versions.toml`. A field added upstream is absent
     * here and fails the test by name, so the commit that adds it also has to give it a control or a [notOffered]
     * reason. The list is regenerated by reading the failure message, not written by hand.
     */
    private val accountedFor =
        setOf(
            "Config.BluetoothConfig.enabled",
            "Config.BluetoothConfig.fixed_pin",
            "Config.BluetoothConfig.mode",
            "Config.DeviceConfig.button_gpio",
            "Config.DeviceConfig.buzzer_gpio",
            "Config.DeviceConfig.disable_triple_click",
            "Config.DeviceConfig.double_tap_as_button_press",
            "Config.DeviceConfig.led_heartbeat_disabled",
            "Config.DeviceConfig.node_info_broadcast_secs",
            "Config.DeviceConfig.rebroadcast_mode",
            "Config.DeviceConfig.role",
            "Config.DeviceConfig.tzdef",
            "Config.DisplayConfig.auto_screen_carousel_secs",
            "Config.DisplayConfig.compass_north_top",
            "Config.DisplayConfig.compass_orientation",
            "Config.DisplayConfig.displaymode",
            "Config.DisplayConfig.flip_screen",
            "Config.DisplayConfig.heading_bold",
            "Config.DisplayConfig.oled",
            "Config.DisplayConfig.screen_on_secs",
            "Config.DisplayConfig.units",
            "Config.DisplayConfig.use_12h_clock",
            "Config.DisplayConfig.wake_on_tap_or_motion",
            "Config.LoRaConfig.bandwidth",
            "Config.LoRaConfig.channel_num",
            "Config.LoRaConfig.coding_rate",
            "Config.LoRaConfig.config_ok_to_mqtt",
            "Config.LoRaConfig.hop_limit",
            "Config.LoRaConfig.ignore_incoming",
            "Config.LoRaConfig.ignore_mqtt",
            "Config.LoRaConfig.modem_preset",
            "Config.LoRaConfig.override_duty_cycle",
            "Config.LoRaConfig.override_frequency",
            "Config.LoRaConfig.pa_fan_disabled",
            "Config.LoRaConfig.region",
            "Config.LoRaConfig.spread_factor",
            "Config.LoRaConfig.sx126x_rx_boosted_gain",
            "Config.LoRaConfig.tx_enabled",
            "Config.LoRaConfig.tx_power",
            "Config.LoRaConfig.use_preset",
            "Config.NetworkConfig.IpV4Config.dns",
            "Config.NetworkConfig.IpV4Config.gateway",
            "Config.NetworkConfig.IpV4Config.ip",
            "Config.NetworkConfig.IpV4Config.subnet",
            "Config.NetworkConfig.address_mode",
            "Config.NetworkConfig.enabled_protocols",
            "Config.NetworkConfig.eth_enabled",
            "Config.NetworkConfig.ntp_server",
            "Config.NetworkConfig.rsyslog_server",
            "Config.NetworkConfig.wifi_enabled",
            "Config.NetworkConfig.wifi_psk",
            "Config.NetworkConfig.wifi_ssid",
            "Config.PositionConfig.broadcast_smart_minimum_distance",
            "Config.PositionConfig.broadcast_smart_minimum_interval_secs",
            "Config.PositionConfig.fixed_position",
            "Config.PositionConfig.gps_en_gpio",
            "Config.PositionConfig.gps_mode",
            "Config.PositionConfig.gps_update_interval",
            "Config.PositionConfig.position_broadcast_secs",
            "Config.PositionConfig.position_broadcast_smart_enabled",
            "Config.PositionConfig.position_flags",
            "Config.PositionConfig.rx_gpio",
            "Config.PositionConfig.tx_gpio",
            "Config.PowerConfig.adc_multiplier_override",
            "Config.PowerConfig.is_power_saving",
            "Config.PowerConfig.on_battery_shutdown_after_secs",
            "Config.PowerConfig.wait_bluetooth_secs",
            "Config.SecurityConfig.admin_key",
            "Config.SecurityConfig.debug_log_api_enabled",
            "Config.SecurityConfig.is_managed",
            "Config.SecurityConfig.private_key",
            "Config.SecurityConfig.public_key",
            "Config.SecurityConfig.serial_enabled",
            "ModuleConfig.AmbientLightingConfig.blue",
            "ModuleConfig.AmbientLightingConfig.current",
            "ModuleConfig.AmbientLightingConfig.green",
            "ModuleConfig.AmbientLightingConfig.led_state",
            "ModuleConfig.AmbientLightingConfig.red",
            "ModuleConfig.AudioConfig.bitrate",
            "ModuleConfig.AudioConfig.codec2_enabled",
            "ModuleConfig.AudioConfig.i2s_din",
            "ModuleConfig.AudioConfig.i2s_sck",
            "ModuleConfig.AudioConfig.i2s_sd",
            "ModuleConfig.AudioConfig.i2s_ws",
            "ModuleConfig.AudioConfig.ptt_pin",
            "ModuleConfig.CannedMessageConfig.inputbroker_event_ccw",
            "ModuleConfig.CannedMessageConfig.inputbroker_event_cw",
            "ModuleConfig.CannedMessageConfig.inputbroker_event_press",
            "ModuleConfig.CannedMessageConfig.inputbroker_pin_a",
            "ModuleConfig.CannedMessageConfig.inputbroker_pin_b",
            "ModuleConfig.CannedMessageConfig.inputbroker_pin_press",
            "ModuleConfig.CannedMessageConfig.rotary1_enabled",
            "ModuleConfig.CannedMessageConfig.send_bell",
            "ModuleConfig.CannedMessageConfig.updown1_enabled",
            "ModuleConfig.DetectionSensorConfig.detection_trigger_type",
            "ModuleConfig.DetectionSensorConfig.enabled",
            "ModuleConfig.DetectionSensorConfig.minimum_broadcast_secs",
            "ModuleConfig.DetectionSensorConfig.monitor_pin",
            "ModuleConfig.DetectionSensorConfig.name",
            "ModuleConfig.DetectionSensorConfig.send_bell",
            "ModuleConfig.DetectionSensorConfig.state_broadcast_secs",
            "ModuleConfig.DetectionSensorConfig.use_pullup",
            "ModuleConfig.ExternalNotificationConfig.active",
            "ModuleConfig.ExternalNotificationConfig.alert_bell",
            "ModuleConfig.ExternalNotificationConfig.alert_bell_buzzer",
            "ModuleConfig.ExternalNotificationConfig.alert_bell_vibra",
            "ModuleConfig.ExternalNotificationConfig.alert_message",
            "ModuleConfig.ExternalNotificationConfig.alert_message_buzzer",
            "ModuleConfig.ExternalNotificationConfig.alert_message_vibra",
            "ModuleConfig.ExternalNotificationConfig.enabled",
            "ModuleConfig.ExternalNotificationConfig.nag_timeout",
            "ModuleConfig.ExternalNotificationConfig.output",
            "ModuleConfig.ExternalNotificationConfig.output_buzzer",
            "ModuleConfig.ExternalNotificationConfig.output_ms",
            "ModuleConfig.ExternalNotificationConfig.output_vibra",
            "ModuleConfig.ExternalNotificationConfig.use_i2s_as_buzzer",
            "ModuleConfig.ExternalNotificationConfig.use_pwm",
            "ModuleConfig.MQTTConfig.address",
            "ModuleConfig.MQTTConfig.enabled",
            "ModuleConfig.MQTTConfig.encryption_enabled",
            "ModuleConfig.MQTTConfig.map_reporting_enabled",
            "ModuleConfig.MQTTConfig.password",
            "ModuleConfig.MQTTConfig.proxy_to_client_enabled",
            "ModuleConfig.MQTTConfig.root",
            "ModuleConfig.MQTTConfig.tls_enabled",
            "ModuleConfig.MQTTConfig.username",
            "ModuleConfig.MapReportSettings.publish_interval_secs",
            "ModuleConfig.MapReportSettings.should_report_location",
            "ModuleConfig.MeshBeaconConfig.broadcast_interval_secs",
            "ModuleConfig.MeshBeaconConfig.broadcast_message",
            "ModuleConfig.NeighborInfoConfig.enabled",
            "ModuleConfig.NeighborInfoConfig.transmit_over_lora",
            "ModuleConfig.NeighborInfoConfig.update_interval",
            "ModuleConfig.PaxcounterConfig.ble_threshold",
            "ModuleConfig.PaxcounterConfig.enabled",
            "ModuleConfig.PaxcounterConfig.paxcounter_update_interval",
            "ModuleConfig.PaxcounterConfig.wifi_threshold",
            "ModuleConfig.RangeTestConfig.enabled",
            "ModuleConfig.RangeTestConfig.save",
            "ModuleConfig.RangeTestConfig.sender",
            "ModuleConfig.SerialConfig.baud",
            "ModuleConfig.SerialConfig.echo",
            "ModuleConfig.SerialConfig.enabled",
            "ModuleConfig.SerialConfig.mode",
            "ModuleConfig.SerialConfig.rxd",
            "ModuleConfig.SerialConfig.timeout",
            "ModuleConfig.SerialConfig.txd",
            "ModuleConfig.StoreForwardConfig.enabled",
            "ModuleConfig.StoreForwardConfig.heartbeat",
            "ModuleConfig.StoreForwardConfig.history_return_max",
            "ModuleConfig.StoreForwardConfig.history_return_window",
            "ModuleConfig.StoreForwardConfig.is_server",
            "ModuleConfig.StoreForwardConfig.records",
            "ModuleConfig.TAKConfig.role",
            "ModuleConfig.TAKConfig.team",
            "ModuleConfig.TelemetryConfig.air_quality_enabled",
            "ModuleConfig.TelemetryConfig.air_quality_interval",
            "ModuleConfig.TelemetryConfig.device_telemetry_enabled",
            "ModuleConfig.TelemetryConfig.device_update_interval",
            "ModuleConfig.TelemetryConfig.environment_display_fahrenheit",
            "ModuleConfig.TelemetryConfig.environment_measurement_enabled",
            "ModuleConfig.TelemetryConfig.environment_screen_enabled",
            "ModuleConfig.TelemetryConfig.environment_update_interval",
            "ModuleConfig.TelemetryConfig.power_measurement_enabled",
            "ModuleConfig.TelemetryConfig.power_screen_enabled",
            "ModuleConfig.TelemetryConfig.power_update_interval",
            "ModuleConfig.TrafficManagementConfig.nodeinfo_direct_response_max_hops",
            "ModuleConfig.TrafficManagementConfig.position_min_interval_secs",
            "ModuleConfig.TrafficManagementConfig.rate_limit_max_packets",
            "ModuleConfig.TrafficManagementConfig.rate_limit_window_secs",
            "ModuleConfig.TrafficManagementConfig.unknown_packet_threshold",
        )

    @Test
    fun `every field named as not offered still exists and still carries a label`() {
        val labelled = labelledFields()
        val stale = notOffered.keys - labelled

        assertTrue(
            stale.isEmpty(),
            "these fields are no longer labelled by the schema, so they cannot still be listed as not offered: " +
                stale.sorted().joinToString(),
        )
    }

    @Test
    fun `every field the schema labels has been accounted for`() {
        val labelled = labelledFields()
        val arrived = labelled - accountedFor
        val departed = accountedFor - labelled

        assertEquals(
            emptySet(),
            arrived,
            "the schema labels these fields and nobody has decided what this app does with them. Give each a control " +
                "or a reason in notOffered, then add it to accountedFor: " +
                arrived.sorted().joinToString(),
        )
        assertEquals(
            emptySet(),
            departed,
            "these fields no longer carry a label upstream, so drop them from accountedFor: " +
                departed.sorted().joinToString(),
        )
    }

    /** `Config.LoRaConfig.hop_limit` for every field of every config message the schema labels. */
    private fun labelledFields(): Set<String> = configMessagePaths()
        .flatMap { path ->
            Class.forName(GENERATED_PACKAGE + path.replace('.', '$')).declaredFields.mapNotNull { property ->
                val tag = property.getAnnotation(WireField::class.java)?.tag ?: return@mapNotNull null
                val label = FieldMetadataRegistry.get(PROTO_PACKAGE + path, tag)?.label
                "$path.${property.name}".takeIf { !label.isNullOrBlank() }
            }
        }
        .toSet()

    /** Proto paths of the message types under `Config` and `ModuleConfig`, read from the protobufs jar's class list. */
    private fun configMessagePaths(): List<String> {
        val jar = File(FieldMetadataRegistry::class.java.protectionDomain.codeSource.location.toURI())
        val prefix = GENERATED_PACKAGE.replace('.', '/')
        return ZipFile(jar).use { zip ->
            zip.entries()
                .asSequence()
                .map { it.name }
                .filter { it.startsWith(prefix) && it.endsWith(".class") && '/' !in it.removePrefix(prefix) }
                .map { it.removePrefix(prefix).removeSuffix(".class").replace('$', '.') }
                .filter { path ->
                    path.split('.').let { it.size > 1 && it.first() in CONTAINERS && it.all(::isTypeName) }
                }
                .filter { Class.forName(GENERATED_PACKAGE + it.replace('.', '$')).enumConstants == null }
                .sorted()
                .toList()
        }
    }

    private fun isTypeName(segment: String) = segment.isNotEmpty() && segment.first().isUpperCase()

    private companion object {
        const val GENERATED_PACKAGE = "org.meshtastic.proto."
        const val PROTO_PACKAGE = "meshtastic."
        val CONTAINERS = setOf("Config", "ModuleConfig")
    }
}
