/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.core.model

import org.jetbrains.compose.resources.StringResource
import org.meshtastic.core.resources.Res
import org.meshtastic.core.resources.allStringResources
import org.meshtastic.proto.Config
import org.meshtastic.proto.MemberRole
import org.meshtastic.proto.ModuleConfig
import org.meshtastic.proto.Team

// Generated by ./gradlew :schema-strings:sync from org.meshtastic:protobufs 2.8.0.116-g51028ca-SNAPSHOT.
// Do not edit: change the schema, then run sync.

/**
 * The schema's label for this enum value, or null where the schema does not name it. A picker shows this in place of
 * the constant's Kotlin name, and falls back to that name when it is null, so a value the schema has not reached still
 * renders.
 */
@Suppress("CyclomaticComplexMethod")
fun Enum<*>.schemaLabelRes(): StringResource? = when (this) {
    is Config.BluetoothConfig.PairingMode -> schemaLabel("schema_bluetooth_pairingmode_")
    is Config.DeviceConfig.RebroadcastMode -> schemaLabel("schema_device_rebroadcastmode_")
    is Config.DeviceConfig.Role -> schemaLabel("schema_device_role_")
    is Config.DisplayConfig.CompassOrientation -> schemaLabel("schema_display_compassorientation_")
    is Config.DisplayConfig.DisplayMode -> schemaLabel("schema_display_displaymode_")
    is Config.DisplayConfig.DisplayUnits -> schemaLabel("schema_display_displayunits_")
    is Config.DisplayConfig.OledType -> schemaLabel("schema_display_oledtype_")
    is Config.LoRaConfig.ModemPreset -> schemaLabel("schema_lora_modempreset_")
    is Config.LoRaConfig.RegionCode -> schemaLabel("schema_lora_regioncode_")
    is Config.NetworkConfig.AddressMode -> schemaLabel("schema_network_addressmode_")
    is Config.NetworkConfig.ProtocolFlags -> schemaLabel("schema_network_protocolflags_")
    is Config.PositionConfig.GpsMode -> schemaLabel("schema_position_gpsmode_")
    is Config.PositionConfig.PositionFlags -> schemaLabel("schema_position_positionflags_")
    is Config.SecurityConfig.PacketSignaturePolicy -> schemaLabel("schema_security_packetsignaturepolicy_")
    is MemberRole -> schemaLabel("schema_memberrole_")
    is ModuleConfig.AudioConfig.Audio_Baud -> schemaLabel("schema_audio_audio_baud_")
    is ModuleConfig.CannedMessageConfig.InputEventChar -> schemaLabel("schema_cannedmessage_inputeventchar_")
    is ModuleConfig.DetectionSensorConfig.TriggerType -> schemaLabel("schema_detectionsensor_triggertype_")
    is ModuleConfig.SerialConfig.Serial_Baud -> schemaLabel("schema_serial_serial_baud_")
    is ModuleConfig.SerialConfig.Serial_Mode -> schemaLabel("schema_serial_serial_mode_")
    is Team -> schemaLabel("schema_team_")
    else -> null
}

/** The schema's one-sentence explanation of this enum value, or null where it has none. */
@Suppress("CyclomaticComplexMethod")
fun Enum<*>.schemaDescriptionRes(): StringResource? = when (this) {
    is Config.DeviceConfig.RebroadcastMode -> schemaDescription("schema_device_rebroadcastmode_")
    is Config.DeviceConfig.Role -> schemaDescription("schema_device_role_")
    is Config.PositionConfig.PositionFlags -> schemaDescription("schema_position_positionflags_")
    is Config.SecurityConfig.PacketSignaturePolicy -> schemaDescription("schema_security_packetsignaturepolicy_")
    else -> null
}

private fun Enum<*>.schemaLabel(prefix: String): StringResource? = Res.allStringResources[prefix + name.lowercase()]

private fun Enum<*>.schemaDescription(prefix: String): StringResource? =
    Res.allStringResources[prefix + name.lowercase() + "_description"]
