/*
 * Copyright (c) 2026 Meshtastic LLC
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */
package org.meshtastic.buildlogic

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.ValueSource
import org.gradle.api.provider.ValueSourceParameters
import org.gradle.api.tasks.CacheableTask
import org.gradle.api.tasks.InputDirectory
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import org.gradle.api.tasks.TaskAction
import java.io.File

/** Locale of the unqualified `values/` directory. */
const val DEFAULT_LOCALE_TAG = "en"

private const val VALUES_PREFIX = "values-"

/** Sorted resource qualifiers (`de`, `pt-rBR`, `b+sr+Latn`) of the `values-*` directories under [resourcesDir]. */
fun localeQualifiers(resourcesDir: File): List<String> = resourcesDir
    .listFiles { file -> file.isDirectory && file.name.startsWith(VALUES_PREFIX) }
    .orEmpty()
    .map { it.name.removePrefix(VALUES_PREFIX) }
    .sorted()

/** BCP 47 tag of an Android resource qualifier: `pt-rBR` → `pt-BR`, `b+sr+Latn` → `sr-Latn`. */
fun qualifierToLanguageTag(qualifier: String): String = when {
    qualifier.startsWith("b+") -> qualifier.removePrefix("b+").replace('+', '-')
    else -> qualifier.replace("-r", "-")
}

// aapt2 filters by literal qualifier, and AndroidX and Material still ship Hebrew as values-iw.
private val LEGACY_QUALIFIER_ALIASES = mapOf("he" to "iw")

/** AGP `localeFilters` for [qualifiers]: `en`, each qualifier, and the legacy alias libraries use for it. */
fun resourceLocaleFilters(qualifiers: List<String>): List<String> =
    listOf(DEFAULT_LOCALE_TAG) + qualifiers + qualifiers.mapNotNull(LEGACY_QUALIFIER_ALIASES::get)

/** `en` plus the BCP 47 tag of every `values-*` directory under [resourcesDir], sorted. */
fun supportedLocaleTags(resourcesDir: File): List<String> =
    (localeQualifiers(resourcesDir).map(::qualifierToLanguageTag) + DEFAULT_LOCALE_TAG).distinct().sorted()

/** Lists the `values-*` qualifiers at configuration time so the configuration cache tracks the directory listing. */
abstract class LocaleQualifiersValueSource : ValueSource<List<String>, LocaleQualifiersValueSource.Params> {
    interface Params : ValueSourceParameters {
        val resourcesDir: DirectoryProperty
    }

    override fun obtain(): List<String> = localeQualifiers(parameters.resourcesDir.get().asFile)
}

/** Generates `supportedLocaleTags` for the Kotlin pickers from the `values-*` directories. */
@CacheableTask
abstract class GenerateSupportedLocalesTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val resourcesDir: DirectoryProperty

    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val tags = supportedLocaleTags(resourcesDir.get().asFile)
        val packageDir = outputDir.get().asFile.resolve("org/meshtastic/core/resources")
        packageDir.deleteRecursively()
        packageDir.mkdirs()
        packageDir
            .resolve("SupportedLocales.kt")
            .writeText(
                buildString {
                    appendLine("// Generated by generateSupportedLocales from the values-* directories. Do not edit.")
                    appendLine("package org.meshtastic.core.resources")
                    appendLine()
                    appendLine("/** BCP 47 tags of every locale the app ships strings for, sorted. */")
                    appendLine("public val supportedLocaleTags: List<String> =")
                    appendLine("    listOf(")
                    tags.forEach { appendLine("        \"$it\",") }
                    appendLine("    )")
                },
            )
    }
}

/** Generates `res/xml/locales_config.xml` for the system per-app language picker. */
@CacheableTask
abstract class GenerateLocaleConfigTask : DefaultTask() {
    @get:InputDirectory
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val resourcesDir: DirectoryProperty

    @get:OutputDirectory abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val tags = supportedLocaleTags(resourcesDir.get().asFile)
        val xmlDir = outputDir.get().asFile.resolve("xml")
        xmlDir.deleteRecursively()
        xmlDir.mkdirs()
        xmlDir
            .resolve("locales_config.xml")
            .writeText(
                buildString {
                    appendLine("<?xml version=\"1.0\" encoding=\"utf-8\"?>")
                    appendLine("<locale-config xmlns:android=\"http://schemas.android.com/apk/res/android\">")
                    tags.forEach { appendLine("    <locale android:name=\"$it\"/>") }
                    appendLine("</locale-config>")
                },
            )
    }
}
