name: Build Debug APK (fdroid)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]  # 想要就加

jobs:
  build-fdroid-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build fdroidDebug
        run: ./gradlew :app:assembleFdroidDebug --parallel --scan

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-fdroid-debug-apk
          path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
          retention-days: 7
