name: Crowdin Upload Sources Action

on:
  push:                  # Watch source strings.xml for changes on main
    paths: [ 'app/src/main/res/values/strings.xml' ]
    branches: [ main ]
  workflow_dispatch:     # Allow manual triggering

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest
    if: github.repository == 'meshtastic/Meshtastic-Android'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload sources with Crowdin
        uses: crowdin/github-action@v2
        with:
          base_url: 'https://meshtastic.crowdin.com/api/v2'
          config: 'config/crowdin/crowdin.yml'
          upload_sources: true
          upload_translations: false
          download_translations: false
          crowdin_branch_name: 'main'
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
